# Project Goal

The goal of this project is to predict whether a loan application will be approved or rejected using classification techniques, and to identify groups of similar loan applicants using clustering techniques.

# Dataset Source

The dataset was obtained from Kaggle.

Dataset Name: Loan Approval Prediction Dataset

Source: Kaggle

URL: https://www.kaggle.com/datasets/priyanshsharma6207/loan-approval-prediction-dataset

# Dataset Description

The dataset contains information about loan applicants and their loan applications.

The dataset contains 13 attributes and 953 instances.

The class attribute is Loan_Status.

In [11]:
import pandas as pd

df = pd.read_csv("Training Dataset.csv")

df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [12]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 953
Number of columns: 13

## Data Types

The following table shows the data type of each attribute in the dataset.

In [13]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

## Class Attribute

The class attribute is Loan_Status.

It contains two classes:
- Y: Loan approved
- N: Loan not approved

In [14]:
df["Loan_Status"].value_counts()

Loan_Status
Y    644
N    309
Name: count, dtype: int64

## Sample of Raw Dataset

The following table shows the first five records of the raw dataset.

In [15]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y